spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    # 数据源
    hikari:
      username: root
      password: CgY1997%!@
      # mysql-connector-java >= 6.x com.mysql.cj.jdbc.Driver
      # mysql-connector-java <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
        metadata:
          instance: c
          haha: hehe
          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: add-bonus
          group: binder-group
  #        namespace: ec51054c-fc24-40db-914f-6b0204d8609e
#        cluster-name: NJ
  #        service: 优先读取这里的服务名 而不是 spring.application.name
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: my-user-center


server:
  port: 8081

logging:
  level:
    com.alibaba.nacos: error
